2.7 Docs Review
couchbaselabs/docs-couchbase-lite pull request #133
Opened 2019-10-17 17:06 UTC by jamiltz

DO NOT MERGE. PR OPENED FOR REVIEW ONLY.

2019-11-29 16:08 UTC, ibsoln commented on modules/ROOT/examples/java-platform/src/com/couchbase/code_snippets/Examples.java
> +        Query query = QueryBuilder.select(SelectResult.all())
```suggestion :: 

The following query will list the existing documents; enabling easy review of server changes being replicated to client

`        Query query2 = QueryBuilder.select(SelectResult.expression(Meta.id),
                        SelectResult.property("language"),
                        SelectResult.property("version"))
                .from(DataSource.database(database))
                .where(Expression.property("type").equalTo(Expression.string("SDK")))
                .orderBy(Ordering.expression(Meta.id));
        try {
            ResultSet rs2 = query2.execute();
            for (Result result : rs2) {
                System.out.println("Student ID :: " + result.getString("id"));
                System.out.println("Learning :: " + result.getString("language") + " version :: "+ result.getFloat("version"));
            }
        } catch (CouchbaseLiteException e) {
            System.out.println(e.getLocalizedMessage());
        }
`

 ```

2019-12-04 09:43 UTC, ibsoln reviewed
test

2019-12-19 11:11 UTC, ibsoln requested changes
I don't understand this PR#133. It seems to be pushing 2.7 changes back into Release 2.6 and I don't believe that is right? 

Can you look at this for me please? @RichardSmedley

2019-12-19 11:11 UTC, ibsoln commented on modules/ROOT/examples/java-platform/src/com/couchbase/code_snippets/Main.java
> +}
@ibsoln TODO?

2019-12-19 11:35 UTC, RichardSmedley commented
Looks like James made this against 2.6 in error - easily done in the GH ui.
I'm closing it.

2019-12-19 11:35 UTC, closed without merging

2019-12-19 13:17 UTC, ibsoln commented
Thanks Richard


From: Richard Smedley <notifications@github.com>
Reply-To: couchbase/docs-couchbase-lite <reply@reply.github.com>
Date: Thursday, 19 December 2019 at 11:35
To: couchbase/docs-couchbase-lite <docs-couchbase-lite@noreply.github.com>
Cc: "Ian Bridge [C]‌" <ian.bridge@couchbase.com>, Mention <mention@noreply.github.com>
Subject: Re: [couchbase/docs-couchbase-lite] 2.7 Docs Review (#133)


Looks like James made this against 2.6 in error - easily done in the GH ui.
I'm closing it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/couchbase/docs-couchbase-lite/pull/133?email_source=notifications&email_token=AMSVPQXJWJK6IEPW5YE6GD3QZNL7XA5CNFSM4JB4RQD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHJKQ2I#issuecomment-567453801>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMSVPQXOKBHMEJ22FORWOVTQZNL7XANCNFSM4JB4RQDQ>.