DOC-6216-Include-Deprecated-List-In-Supported-OsVersions
couchbaselabs/docs-couchbase-lite pull request #176
Opened 2020-01-30 09:01 UTC by ibsoln

https://issues.couchbase.com/browse/DOC-6216

Support for Android API 19 and 21 is deprecated in this release and will 
be removed in a future release

2020-01-30 13:53 UTC, rajagp requested changes
Can you ensure this notice shows up for 2.6 and 2.7 please. Once done. good to go

2020-01-30 15:15 UTC, ibsoln commented
> Can you ensure this notice shows up for 2.6 and 2.7 please. Once done. good to go

@rajagp Of course. If you can approve then I'll cherry-pick it back to 2.6 as well as applying to 2.7

2020-02-03 09:59 UTC, ibsoln commented
> Can you ensure this notice shows up for 2.6 and 2.7 please. Once done. good to go

@rajagp see also https://github.com/couchbase/docs-couchbase-lite/pull/179 which applies the change to 2.6 also

2020-02-05 08:04 UTC, ibsoln commented
@rajagp can you clear the requested change so I can get this merged please?

2020-02-05 08:08 UTC, ibsoln commented
Now superseded by https://github.com/couchbase/docs-couchbase-lite/pull/183

2020-02-05 08:08 UTC, closed without merging