DOC-7645 - Release Notes 2.8.1 iOS
couchbaselabs/docs-couchbase-lite pull request #348
Opened 2020-11-11 14:35 UTC by ibsoln

https://issues.couchbase.com/browse/DOC-7645

2020-11-12 17:21 UTC, amarantha-k approved these changes

2020-11-12 17:26 UTC, djpongh requested changes
These are the release notes for 2.8.1 Android/Java not 2.8.1 iOS.

2.8.1 iOS has the following issues fixed:
https://issues.couchbase.com/browse/CBL-1423
https://issues.couchbase.com/browse/CBL-1403

2020-11-12 17:40 UTC, ibsoln commented
> These are the release notes for 2.8.1 Android/Java not 2.8.1 iOS.
> 
> 2.8.1 iOS has the following issues fixed:
> https://issues.couchbase.com/browse/CBL-1423
> https://issues.couchbase.com/browse/CBL-1403

HI @djpongh The issue fixed for iOS are in: 

- https://github.com/couchbase/docs-couchbase-lite/pull/348/files#diff-23c42c4fac369303be3f64f553ae218774d536102ffaa46d8504fc6f1737382e
- https://github.com/couchbase/docs-couchbase-lite/pull/348/files#diff-8be2805ec669d0c0ba948aad78a2311822107a3f4283af1fedb8bf97eeeb199f

2020-11-13 17:09 UTC, djpongh approved these changes

2020-11-13 17:38 UTC, merged