DOC-8272-C4-Code --N1QL Code Snippets
couchbaselabs/docs-couchbase-lite pull request #524
Opened 2021-09-08 12:24 UTC by ibsoln

https://issues.couchbase.com/browse/DOC-8272

2021-09-08 12:27 UTC, ibsoln commented
If you've time can you  please check N1QL query additions on Java/Kotlin (@bmeike ), C (@borrrden ) and obj-C (@jayahariv )

2021-09-10 01:00 UTC, borrrden requested changes

2021-09-10 01:00 UTC, borrrden commented on modules/c/examples/code_snippets/main.c
> +    */
Please do not do this.  Do what many of the others do and actually write this line in.  I want to keep this file compilable, and this is a compiler error down on line 830.  If you are unsure, it might be a good exercise to try to compile it.  If I am on Linux, or WSL on Windows, I install the `.deb` package, and then simply run `gcc main.c -lcblite -Wall -Wno-unused-function`

2021-09-10 01:00 UTC, borrrden commented on modules/c/examples/code_snippets/main.c
> +    n1qlparams = FLMutableDict_New();
This is not valid C (there is no type declared)

2021-09-10 01:00 UTC, borrrden commented on modules/c/examples/code_snippets/main.c
> +    FLSTR n1qlstr = "SELECT * FROM _ WHERE type = $type";
`FLSTR` is not a type, and a slice cannot be directly set from a `const char *` anyway.

2021-09-11 15:54 UTC, closed without merging