DOC-4451
couchbaselabs/docs-couchbase-lite pull request #76
Opened 2019-03-25 14:42 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-4451

2019-04-26 16:02 UTC, eric-schneider requested changes
There are issues with the code callouts, and other minor edits to be made.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +include::{snippet}[tag=replication-pull-filter,indent=0]
The `<1>` callout is not present within the `replication-pull-filter` region of the snippets for Java, C#, and Objective-C. (It only appears in the snippet for Swift.) Therefore the callout seems orphaned beneath the code blocks.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +Otherwise, long running functions would considerably slow down the replicator.
```suggestion
Otherwise, long running functions would slow down the replicator considerably.
```
Personal opinion: I feel like this reads better.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +Examples of push or pull filters include:
```suggestion
```

Personal opinion: This sentence doesn't seem necessary.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +For instance, high-priority docs could be pushed first, or docs in a "draft" state could be skipped.
```suggestion
For instance, high-priority documents could be pushed first, or documents in a "draft" state could be skipped.
```

We probably shouldn't ever abbreviate the word 'documents'. It looks like you don't abbreviate it anywhere else on the page, so using 'documents' is more consistent anyway.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +Otherwise, long running functions would considerably slow down the replicator.
```suggestion
Otherwise, long running functions would slow down the replicator considerably.
```

Personal opinion: I feel like this reads better.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +Sync Gateway xref:sync-gateway::data-routing.adoc[channels] are designed to be scalable (documents are filtered on the server) where as a pull replication filter is applied to a document once it has
```suggestion
Sync Gateway xref:sync-gateway::data-routing.adoc[channels] are designed to be scalable (documents are filtered on the server) whereas a pull replication filter is applied to a document once it has been downloaded.
```

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +include::{snippet}[tag=replication-pull-filter,indent=0]
Which makes me think that the AsciiDoctor [documentation for callouts](https://asciidoctor.org/docs/user-manual/#callouts) is misleading or even outright wrong:

> Each callout number used in a verbatim block **must appear twice**. The first use, which goes within the verbatim block, marks the line being annotated (i.e., the target). The second use, which goes below the verbatim block, defines the annotation text.

Based on this definition, I would assume that a callout would not render unless it is specified both inside and outside of the verbatim block.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function].
```suggestion
<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function^].
```

Any link that takes you outside of the docs should open in a new tab.

2019-04-26 16:02 UTC, eric-schneider commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function].
```suggestion
<1> The callback should follow the semantics of a https://en.wikipedia.org/wiki/Pure_function[pure function^].
```

Any link that takes you outside of the docs should open in a new tab.

2019-04-29 13:22 UTC, jamiltz commented on modules/ROOT/examples/java/app/src/main/java/com/couchbase/code_snippets/MainActivity.java
> +        config.setPullFilter(new ReplicationFilter() {
```suggestion
        config.setPullFilter(new ReplicationFilter() { // <1>
```

2019-04-29 13:22 UTC, jamiltz commented on modules/ROOT/examples/objc/code-snippets/SampleCodeTest.m
> +    config.pullFilter = ^BOOL(CBLDocument * _Nonnull document, CBLDocumentFlags flags) {
```suggestion
    config.pullFilter = ^BOOL(CBLDocument * _Nonnull document, CBLDocumentFlags flags) { // <1>
```

2019-04-29 13:22 UTC, jamiltz commented on modules/ROOT/examples/csharp/Program.cs
> +            config.PullFilter = (document, flags) =>
```suggestion
            config.PullFilter = (document, flags) => // <1>
```

2019-04-29 13:24 UTC, jamiltz commented on modules/ROOT/pages/_partials/replication-filters.adoc
> +include::{snippet}[tag=replication-pull-filter,indent=0]
Done in https://github.com/couchbase/docs-couchbase-lite/pull/76/commits/828d191a6d291c341b6ca93813feba2e94d983b1

2019-04-29 13:27 UTC, jamiltz commented
@eric-schneider Thanks!

2019-04-29 13:28 UTC, merged