CBL-4041: [C] Code Samples for FTS and Indexing
couchbaselabs/docs-couchbase-lite pull request #775
Opened 2023-01-18 16:15 UTC by velicuvlad

2023-01-18 16:16 UTC, velicuvlad commented
@osfameron

2023-01-25 11:34 UTC, osfameron requested changes

2023-01-25 11:34 UTC, osfameron commented on modules/c/examples/code_snippets/main.c
> -// tag::console-logging[]
What's happened to this one?

2023-01-25 11:34 UTC, osfameron commented on modules/c/examples/code_snippets/main.c
> -// tag::console-logging-db[]
Looks like this one has been removed, but that should be OK, as the code snippet is hidden in an `ifndef::is_c`

2023-01-25 11:47 UTC, velicuvlad commented
in C, if the level of logging is changed, it changes across all domains - i.e cannot be individually set per domain. Snippets of such behaviour are under `tag::logging[]`.

If desired, I can add that tag (`tag::console-logging-db[]`) back but it will remain empty and deleted at some point in future as atm I believe we are looking forward to only keep changing the log level across all domains for all platforms (i.e. current behaviour of C)

2023-01-25 11:50 UTC, osfameron commented
Thanks for the clarification @velicuvlad !
I'll merge now, we may need to review some of the text to signal that possibly.

2023-01-25 11:50 UTC, merged