DOC-10694-.Net-Data-Sync-Peer-to-Peer
couchbaselabs/docs-couchbase-lite pull request #788
Opened 2023-02-16 12:29 UTC by franrob-projects

- Improves 'Active' voice
- Improves language clarity 
- Improves product naming consistency

2023-02-16 16:31 UTC, dinaabennett approved these changes
Ok :-)

2023-02-16 18:20 UTC, osfameron requested changes
There's a couple of changes I've marked "Careful" that might be worth reviewing before merge, as they might unintentionally change technical meaning slightly.

Other bits are nitpicking about commas, less urgent.

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-custom.adoc
> +You must purchase the Enterprise License, which includes official https://www.couchbase.com/support-policy[Couchbase Support]. To use it in production (also see the https://www.couchbase.com/licensin
Ventilate!

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-custom.adoc
> +At this point, the connection is established, and both Peers are ready to exchange data.
remove comma

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-custom.adoc
> +The replication connection's `receive` method is called, which then processes the data to persist to the local database.
maybe new sentence instead of comma?

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-query-n1ql-mobile-server-diffs.adoc
> +These instances are listed below.
NB "below" see style guide

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-active.adoc
> +Specifically it covers the implementation of a {glos-term-active-peer}.
CAREFUL: https://docs.couchbase.com/couchbase-lite/current/android/p2psync-websocket-using-active.html#introduction the term is "Active Peer", so "an" was correct.

(This is one of the reasons that I was complaining about confusingly named fragments for keywords...)

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-active.adoc
> +For the active Peer this involves browsing-for and selecting the appropriate service using a zero-config protocol such as _Bonjour_-- see: https://developer.apple.com/bonjour/.
If you have "Passive" capitalised, you probably want "Active" too?

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-passive.adoc
> +<.> Optionally, choose to sync only changes. The default is not to enable delta-sync -- see: <<delta-sync>>.
Ventilate

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-passive.adoc
> +Here we show the default TLS authentication, which is an anonymous self-signed certificate.
Careful here, as "by" means "using" doesn't it?
Hmm, "an" sort of works, so probably OK

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-passive.adoc
> +However, it _can_ be disabled, for example, for development and-or test environments.
Again I think that comma is extraneous?
Could split new sentence before "for example" instead?

Also note "and-or" (a weird idiosyncracy you see sometimes in  mobile docs, should probably be "and/or" or just "or")

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket.adoc
> +* Certificate Authority (CA)
Careful: "CA Cert" is a technical phrase.

A "CA" is the authority. 
A "CA Cert" is a specific sort of certificate relating to the authority.

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket.adoc
> +* Anonymous Self-sign -- an auto-generated anonymous TLS identity is generated if no identity is specified.
Careful. "Anonymous self-signed" seems to be the phrase I've seen used.

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket.adoc
> +The authentication mechanism is defined at the endpoint level, meaning that it is independent of the replicated database.
Bit careful here: "database being replicated" might be more specific?

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket.adoc
> +TLS and its associated keys and certificates require using secure storage to minimize the chances of a security breach.
Hmm, not sure if "the use of" might actually be warranted here...
The TLS spec itself doesn't require this, it's more a best practice.
@dinaabennett what do you think?

2023-02-16 18:20 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket.adoc
> +// DO NOT EDIT OR REMOVE
Do you not want to remove that warning? I kinda do... 😛

2023-03-14 17:51 UTC, osfameron commented on modules/ROOT/pages/_partials/commons/common-p2psync-websocket-using-active.adoc
> +Use the `{url-api-class-replicator-config-basic-auth}` to supply basic authentication credentials (username and word).
hmm?

2023-03-14 17:51 UTC, osfameron approved these changes
👍

2023-03-14 17:51 UTC, merged