Dotnet supported 3.1
couchbaselabs/docs-couchbase-lite pull request #791
Opened 2023-03-03 17:48 UTC by osfameron

2023-03-03 17:51 UTC, dinaabennett approved these changes

2023-03-07 22:14 UTC, borrrden requested changes

2023-03-07 22:14 UTC, borrrden commented on modules/ROOT/pages/_partials/supported-versions.adoc
> +NOTE: Support for API 19, API 20 and API 21 is deprecated and will be removed in a future release; you should plan to migrate as soon as possible.
This is no longer needed as API 22 is the min version listed above.

2023-03-08 07:32 UTC, osfameron commented
Addressed one change from @borrrden, can I get a re-review to merge?

2023-03-08 12:52 UTC, dinaabennett approved these changes
:-)

2023-03-09 01:31 UTC, borrrden approved these changes
I am pretty sure I will need another change later but I will file another PR at that time.

2023-03-09 09:43 UTC, merged