Doc 10251-Update-Replication-Page
couchbaselabs/docs-couchbase-lite pull request #799
Opened 2023-03-30 19:30 UTC by dinaabennett

Update Replication page with information for Scopes and Collections

2023-03-31 18:26 UTC, pasin requested changes

2023-03-31 18:26 UTC, pasin commented on modules/ROOT/pages/_partials/commons/common-sgw-replication.adoc
> +image:ROOT:cbl-replication-scopes-collections-2.png[Sync Couchbase Lite default collection with default collection on Sync Gateway,500,,align="left"]
I think this section can be either removed or change the diagram by adding `Collections: _default` under the `Target:`

2023-03-31 18:26 UTC, pasin commented on modules/ROOT/pages/_partials/commons/common-sgw-replication.adoc
> +image:ROOT:cbl-replication-scopes-collections-3.png["Syncing scope with user-defined collections. Couchbase Lite has fewer collections than the Sync Gateway configuration (no collection filters)",500
This diagram is not correct. As I have already mentioned in the Google Doc that CBL 3.1 doesn't allow to specify only scope to have all collection in the scope synced. The diagram need to specify collection A and C. 

- Remove the description "All collections in Sample ...."
- Add "Collections: A, C" under "Target: ..."

2023-03-31 18:26 UTC, pasin commented on modules/ROOT/pages/_partials/commons/common-sgw-replication.adoc
> +
In the diagram, change "Filter: C" to "Collections: A"

2023-04-01 04:14 UTC, pasin approved these changes

2023-04-04 15:36 UTC, osfameron approved these changes
🥳

2023-04-04 15:36 UTC, merged