Doc 11010  various fixes
couchbaselabs/docs-couchbase-lite pull request #808
Opened 2023-04-20 18:18 UTC by franrob-projects

Various fixes for release 3.1

1. Updates property
2. Updates ref note]
3. Updates code
4. Updates code `it.collection`
5. Removes annotation
6. Determines antecedent
7. Removes text
8. Removes broken include and replaces with the tagged code

Thanks

2023-04-20 21:37 UTC, bmeike requested changes
Couple of things are not quite right yet...

2023-04-20 21:37 UTC, bmeike commented on modules/ROOT/pages/_partials/commons/common-document.adoc
> +fun watchQuery(query: Query): LiveData<List<Result>> {
AKKK! Please... lets not put code in the adoc files.  I can change the source....

2023-04-20 21:37 UTC, bmeike commented on modules/ROOT/pages/_partials/commons/common-document.adoc
> +        // end::flow-as-database-change-listener[]
Same deal.  Let's fix the code to which this points and not get code where it can't be verified.

2023-04-20 21:37 UTC, bmeike commented on modules/android/examples/GetStartedKotlin/app/src/main/java/com/couchbase/android/getstarted/kotlin/DBManager.kt
> +    // Retrieve immutable document update `language` property
missing an "and"?

2023-04-20 21:37 UTC, bmeike commented on modules/android/examples/codesnippet_collection.kt
> +        CouchbaseLite.init(this code)
Huh?  No.  I sent some code that should replace this...

2023-04-20 21:37 UTC, bmeike commented on modules/android/pages/kotlin.adoc
> +    .map { it.collection.getDocument(it.collection)?.getString("lastModified") }
I'm pretty sure that this change is a mistake.... I think it should stay "documentID"

2023-04-21 13:18 UTC, franrob-projects commented
Hi @bmeike. I've amended this as per your feedback. I attempted to fix the code that points to the `tag:: code` but was unsuccessful. Can we work together to fix it? I'd like to learn how you will go about this :). Thanks

2023-04-21 19:11 UTC, bmeike commented
@franrob-projects Absolutely.  Happy to show you.

2023-04-28 17:18 UTC, bmeike approved these changes
Awesome.  Thanks for doing this!

2023-05-02 17:19 UTC, bmeike commented
Hey... this is good go go, by me.

2023-05-03 08:19 UTC, merged