DOC-12385: Copy across missing snippets
couchbaselabs/docs-couchbase-lite pull request #891
Opened 2024-07-25 14:40 UTC by ElliotFrancisHunter

Move snippets from p2psync-websocket.cs to Program.cs

2024-07-30 22:29 UTC, borrrden commented
This has broken compilation and cannot be merged

2024-07-30 22:31 UTC, borrrden requested changes
This needs to be written in a way that matches the existing code in Program.cs.  It _cannot_ just be plopped in.  This is what the GH checks are meant to prevent.  These snippets should be able to be compiled.

2024-07-31 08:19 UTC, osfameron commented
Thanks @borrrden - who of the devs can we ask to look at that?
Can you let us know which ticket type to create and link to the DOC ticket above?

2024-07-31 22:09 UTC, borrrden commented
Ideally it would be the person who wrote them that puts them in correctly.  Otherwise it's going to be me.  Are all of these snippets needed?  Some of them are just one line which seems a bit excessive to create an entire self contained snippet for.

2024-08-09 22:14 UTC, borrrden reviewed
Would like some clarification here on whether these are all important.  There are a lot of tags in here including "how to call start" which seems pretty obvious, does it really need a snippet?

Anyway perhaps a description of what each one wants to do is in order because some of them are suspicious.  I'll put in comments inline.

2024-08-09 22:15 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> +    // . . . other code . . .
What is this meant to represent?

2024-08-09 22:16 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> +thisConfig.Continuous = true; // default value
This is not the default for this property

2024-08-09 22:16 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> + thisReplicator.Start(); // <.>
This is the same as starting any other replicator...does it really need a separate snippet?

2024-08-09 22:17 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
>  // Only CA Certs accepted
Misleading comment here.  Only certificates issued by this CA are accepted, not any CA cert.

2024-08-09 22:17 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> +        Thread.Sleep(200);
This is quite domain specific and unlikely to make a helpful snippet

2024-08-09 22:17 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> +_thisDatabase.Close();
Why does this need to be here?

2024-08-09 22:18 UTC, borrrden commented on modules/csharp/examples/code_snippets/Program.cs
> +thisReplicator.Stop(); // <.>
Same as any other replication...

2024-10-17 15:24 UTC, closed without merging

2024-10-17 15:25 UTC, ElliotFrancisHunter commented
Closed as underlying issue has been fixed. Will still need to move these snippets over at some point.