DOC-12646: fix namespace, add MAUI snippet, remove dead attribute
couchbaselabs/docs-couchbase-lite pull request #924
Opened 2024-10-18 08:43 UTC by ElliotFrancisHunter

A PR to resolve the following ticket: https://couchbasecloud.atlassian.net/browse/DOC-12646.

Change List:

- Added admonition informing users Couchbase Lite must be activated before other CBL calls
- Added MAUI snippet
- Corrected `Android` namespace to `Droid`

2024-10-19 00:05 UTC, borrrden requested changes, later dismissed

2024-10-19 00:05 UTC, borrrden commented on modules/csharp/pages/gs-install.adoc
> +* `Couchbase.Lite.Enterprise.Support.Droid`
Same comment as other PR

2024-10-19 00:05 UTC, borrrden commented on modules/csharp/pages/gs-install.adoc
> +* `Couchbase.Lite.Support.Droid`
Here too, this is also a package name

2024-10-22 14:35 UTC, osfameron approved these changes
Same as #923, lgtm if I've understood the previous discussion

2024-10-22 15:15 UTC, merged