DOC-12761: Add new features from 3.2.1 to what's new page
couchbaselabs/docs-couchbase-lite pull request #933
Opened 2024-11-20 17:48 UTC by ElliotFrancisHunter

PR to add features introduced in 3.2.1 to the what's new page. Also linked out to the source documentation material per platform

2024-11-20 17:58 UTC, ElliotFrancisHunter commented
Build failure has already been addressed in another PR and is unrelated to docs.

2024-11-22 12:12 UTC, simon-dew requested changes, later dismissed
Just one minor correction and one comment

2024-11-22 12:12 UTC, simon-dew commented on modules/ROOT/pages/cbl-whatsnew.adoc
> +You can use UNNEST in queries to unpack arrays within a document into individual rows. This capability makes it possible to join them with its parent object in the query.
Number agreement

```suggestion
You can use UNNEST in queries to unpack arrays within a document into individual rows. This capability makes it possible to join them with their parent object in the query.
```

2024-11-22 12:12 UTC, simon-dew commented on modules/ROOT/pages/cbl-whatsnew.adoc
> +UNNEST is used within the FROM clause and can be chained to perform multi-level UNNEST.
These (FROM clause, chaining UNNESTs) are separate but related ideas. I think I'd prefer them to be two separate sentences. I'm not going to insist on it though.

2024-11-22 12:23 UTC, ElliotFrancisHunter commented on modules/ROOT/pages/cbl-whatsnew.adoc
> +UNNEST is used within the FROM clause and can be chained to perform multi-level UNNEST.
Done

2024-11-22 12:36 UTC, simon-dew approved these changes
LGTM 👍

2024-11-22 14:06 UTC, merged