DOC-12818 support compat 4 0
couchbaselabs/docs-couchbase-lite pull request #940
Opened 2024-12-05 17:54 UTC by ElliotFrancisHunter

Platform support and compatibility updates for CBL 4.0.

Updated URL for all Supported versions and Environments: [CBL 4.0 Supported Environments and Compatibility](https://preview.docs-test.couchbase.com/docs-couchbase-lite-DOC-12818-support-compat-4-0/couchbase-lite/current/csharp/supported-os.html)

Support matrix resource here: https://docs.google.com/spreadsheets/d/1wali82budYZrMQn7CIoEl6t7cCLNAHtfdcNVrGgJpR0/edit?gid=782272081#gid=782272081

# Preview Credentials: https://couchbasecloud.atlassian.net/wiki/spaces/DOCS/pages/1971224949/Docs+Team+demo+site+passwords

## Changed Pages
-------------------
1. Compatibility Matrix pages

* Android - https://preview.docs-test.couchbase.com/docs-couchbase-lite-DOC-12818-support-compat-4-0/couchbase-lite/current/android/compatibility.html
* C - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/c/compatibility.html
* .NET - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/csharp/compatibility.html
* Java - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/java/compatibility.html
* Objective-C - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/objc/compatibility.html
* Swift - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/swift/compatibility.html

2. Supported Platforms

* Android - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/android/supported-os.html
* C - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/c/supported-os.html
* .NET - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/csharp/supported-os.html
* Java - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/java/supported-os.html
* Objective-C - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/objc/supported-os.html
* Swift - https://preview.docs-test.couchbase.com/sgw40compat/couchbase-lite/current/swift/supported-os.html

-------------------
## Pages still needing changes/updates
-----------------------

- (Unsure if it requires any updates) Supported Environments: https://preview.docs-test.couchbase.com/sgw40compat/sync-gateway/current/supported-environments.html

-----------------------

2025-09-15 16:28 UTC, pasin commented
@borrrden Could you verify .NET support matrix in the doc's preview?

2025-09-15 16:29 UTC, pasin submitted a review, later dismissed
@iamfortune , here is the support matrix for CBL-Android, iOS, and C. For .NET, we need @borrrden to verify.

CBL-Android 3.3 / 4.0 : 
- API 24 (Min)

iOS (Objective-C / Swift) 3.3 / 4.0
- iOS : 15 (Min)
- macOS 13 (Min)

C : 4.0
- iOS : 15 (Min)
- macOS 13 (Min)
- Android : API 24 (Min)
- Linux : Debian / Raspbian 11 - 13, Ubuntu 24
- Wins : 10, 11

2025-09-16 15:05 UTC, iamfortune commented
. @pasin Done! I've added the support matrix for CBL-Android, iOS, and C as specified. Ready for @borrrden  to verify the .NET details when available.

2025-09-16 22:17 UTC, borrrden commented
There have been no updates to the .NET support table so naturally they are mostly wrong now.  Xamarin has been removed already since 3.2 so it doesn't need an entry.  All others need to go from .NET 8 to .NET 9 *except* for Console Vanilla.

Note that the OS support WILL mirror the others as much as possible.  Since Swift / Objective-C has moved to iOS 15, so too shall .NET.  Since Android has moved to API24+, so too shall .NET.  macOS will also move to 13.

2025-09-17 01:20 UTC, iamfortune commented
@borrrden I've just pushed the changes you mentioned and requested a review, kindly take a look, thank you.

2025-09-17 22:13 UTC, borrrden approved these changes

2025-09-18 11:29 UTC, rakhi-prathap requested changes
Just a few comments, mostly around merge conflicts.

2025-09-18 11:29 UTC, rakhi-prathap commented on modules/c/pages/gs-downloads.adoc
> +<<<<<<< HEAD
Looks like a merge conflict. Please check.

2025-09-18 11:29 UTC, rakhi-prathap commented on modules/c/pages/gs-downloads.adoc
> +<<<<<<< HEAD
Same here, more merge conflicts.

2025-09-18 11:29 UTC, rakhi-prathap commented on modules/ROOT/pages/_partials/commons/common-compatibility.adoc
> +include::partial$compatibility-cbl-sgw.adoc[]
Not sure if I'm understanding this right. When I look at the preview site, I do not see CBL 4.0 in the compatibility matrix. Is that how it's supposed to be?

2025-09-18 11:44 UTC, iamfortune commented on modules/c/pages/gs-downloads.adoc
> +<<<<<<< HEAD
Yes, On a todo with Hakim for later

2025-09-18 11:44 UTC, iamfortune commented on modules/c/pages/gs-downloads.adoc
> +<<<<<<< HEAD
Same here, to be fixed with Hakim for later

2025-09-18 14:16 UTC, rakhi-prathap approved these changes

2025-09-18 15:47 UTC, merged